// Code generated by "go run gen_dtype.go"; DO NOT EDIT.
package types

import "unsafe"

func (dt DTString) DType() DType {
	return DString
}

func (dt DTString) ItemSize() int {
	return int(unsafe.Sizeof(dt))
}
