// Code generated by "go run gen_dtype.go"; DO NOT EDIT.
package types

import "unsafe"

func (dt DTFloat32) DType() DType {
	return DFloat32
}

func (dt DTFloat32) ItemSize() int {
	return int(unsafe.Sizeof(dt))
}

func (dt DTFloat64) DType() DType {
	return DFloat64
}

func (dt DTFloat64) ItemSize() int {
	return int(unsafe.Sizeof(dt))
}
